### PR TITLE
Add runners to the database to track runs, rbi

### PR DESCRIPTION
**Pull request by davestern**
The `<runner>` tag has runner events for every at-bat, as well as attributes to specify whether the runner scored, the run was earned and if the batter gets an RBI.

Now queries like this are possible for RBI:
```

mysql> SELECT
    -> ab.batter,
    -> CONCAT(p.first_name,' ',p.last_name) as name,
    -> sum(r.rbi) as rbi
    -> FROM runner r
    -> LEFT JOIN atbat ab on ab.game_id = r.game_id AND ab.num = r.atbat
    -> LEFT JOIN game g on ab.game_id = g.game_id
    -> LEFT JOIN player p on ab.batter = p.id
    -> WHERE
    ->     YEAR(g.date) = '2015'
    -> GROUP BY batter
    -> ORDER BY sum(r.rbi) DESC
    -> LIMIT 10;
+--------+-------------------+------+
| batter | name              | rbi  |
+--------+-------------------+------+
| 571448 | Nolan Arenado     |  130 |
| 518626 | Josh Donaldson    |  123 |
| 448801 | Chris Davis       |  117 |
| 430832 | Jose Bautista     |  114 |
| 429665 | Edwin Encarnacion |  111 |
| 502671 | Paul Goldschmidt  |  110 |
| 120074 | David Ortiz       |  107 |
| 434778 | Kendrys Morales   |  106 |
| 493316 | Yoenis Cespedes   |  105 |
| 502110 | J.D. Martinez     |  102 |
+--------+-------------------+------+
```

Or like this for earned runs:
```
mysql> SELECT
    -> r.pitcher_credited as pitcher,
    -> CONCAT(p.first_name,' ',p.last_name) as name,
    -> sum(r.earned) as 'earned runs'
    -> FROM runner r
    -> LEFT JOIN atbat ab on ab.game_id = r.game_id AND ab.num = r.atbat
    -> LEFT JOIN game g on ab.game_id = g.game_id
    -> LEFT JOIN player p on p.id = r.pitcher_credited
    -> WHERE
    ->     YEAR(g.date) = 2015
    -> GROUP BY pitcher_credited
    -> ORDER BY sum(r.earned) DESC
    -> LIMIT 10;
+---------+------------------+-------------+
| pitcher | name             | earned runs |
+---------+------------------+-------------+
|  502188 | Jeff Samardzija  |         118 |
|  407890 | Colby Lewis      |         105 |
|  430580 | Alfredo Simon    |         104 |
|  452718 | Kyle Kendrick    |         100 |
|  346798 | Kyle Lohse       |          99 |
|  523989 | Rubby De La Rosa |          98 |
|  425386 | Jeremy Guthrie   |          98 |
|  501957 | Chris Tillman    |          96 |
|  489119 | Wade Miley       |          96 |
|  519144 | Rick Porcello    |          94 |
+---------+------------------+-------------+
```

Note that the data is still slightly off. Part of the reason is commented in the code - we can't account for pinch runners. There also may be slight discrepancies I haven't found yet. Of the top 10 RBI leaders, for example, David Ortiz is off by 1, but the others are correct. I'll be looking to figure this out, but this PR is 99% of the way there.

### CODE REVIEW

**Comment by wellsoliver** [comment]
Hmm, my only concern here is MySQL-specific syntax w/ the REPLACE INTO-- any chance you can modify that to be more general?

**Comment by davestern** [comment]
Sure, but I got that from existing code. The existing code already uses it for almost all database write operations. Example:

https://github.com/wellsoliver/py-gameday/blob/master/lib/players.py#L16

**Comment by wellsoliver** [comment]
Oh you're right. It's been a while. Nevermind then!

**Comment by davestern** [comment]
No worries. BTW, great work on this. I'm actively using it, so hope you don't mind all the updates. I have more coming.

**Comment by wellsoliver** [comment]
not at all-- have at it

**Comment by davestern** [comment]
Closed but not merged?

**Comment by wellsoliver** [comment]
I  merged it, didn't I? I think I did

**Comment by wellsoliver** [comment]
Yeah https://github.com/wellsoliver/py-gameday/commit/ab6c8f80262d85b590cb7ab51d45eea34782bb6f

**Comment by davestern** [comment]
That was PR #7. This is PR #8.

**Comment by wellsoliver** [comment]
ah yeah. Done!

**Pull request merged**
